# Generated by Django 4.2.1 on 2023-06-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': "Maktab o'quvchilari",
                'verbose_name_plural': "Maktab o'quvchilari",
                'ordering': ['id'],
            },
        ),
    ]
