# Generated by Django 4.2.1 on 2023-06-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='age',
            field=models.BigIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='pupil',
            name='class_name',
            field=models.CharField(default='1A', max_length=6),
        ),
        migrations.AddField(
            model_name='pupil',
            name='friday',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='monday',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='monthly',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='saturday',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='thursday',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='tuesday',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='wednesday',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='weekly',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='year',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
